apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-node
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api-node
  template:
    metadata:
      labels:
        app: api-node
    spec:
      containers:
        - name: api-node
          image: api-node-simples
          imagePullPolicy: Never
          ports:
            - containerPort: 3000